### ISSUE TITLE
nbt parsing error with get_nbt_data(db, player_keys)

### ISSUE THREAD

**Issue by Breeze1074** [reedacartwright/rbedrock#3]
There appears to be an error parsing player_keys data with the get_nbt_data function. This may be related to the 1.18.30 update as I did not have this occur several days previously.

`> db <- bedrockdb(dbpath)
> player_keys <- get_keys(db, starts_with = "player_server_")
> player_data <- get_nbt_data(db, player_keys)
Error in read_rnbt(rawdata) : 
  embedded nul in string: '\0\0\0\006\0\0\0\001'`

**Comment by reedacartwright** [comment]
I don't have access to 1.18.30 at the moment. Can you upload an small world that has this problem and tell me what key has the issue?

**Comment by Breeze1074** [comment]
Sure, here's a skyblock world I noticed the issue with. The key matches "player_server_". I can't upload directly so here's a google drive link: 
https://drive.google.com/file/d/17e-EqNfjYAnFFlBsnxXrK5dLgHr8h0E1/view?usp=sharing

**Comment by reedacartwright** [comment]
It turns out that there is now a `StorageKey` element in the player_server's NBT data and it can contain embedded NULLs. I need to escape them to keep R happy.

**Comment by Breeze1074** [comment]
Interesting. I'm also noticing that rbedrock is finding far fewer entity tags, but this might be corrupted chunks. I'll dig around more tomorrow with clean world data and open a separate issue if I confirm.
