### ISSUE TITLE
Error in read_rnbt(rawdata): Malformed NBT data with tag `128`: at nbt.c, line 251.

### ISSUE THREAD

**Issue by Inkybro** [reedacartwright/rbedrock#4]
I'm getting this error when attempting to run `get_nbt_data` - it appears, possibly, to be related to certain chunk tags, but then again, I also get this error without a chunk tag mentioned. Clearly, in at least the cases demonstrated below, `read_rnbt` is supplied with raw data that it considers malformed for its purposes.

I did wonder if this is at all related to the issue I saw posted/resolved yesterday. I did remove and re-install my copy of rbedrock (my version is now at 0.2.0) - I got the same results, before re-installing and after, but perhaps 0.2.0 doesn't actually include the fix for yesterday's issue, and so perhaps this is meaningless information :P

Here are some examples:

```R
> chunk_keys <- rbedrock::get_keys(db)

> nbt <- rbedrock::get_nbt_data(db, chunk_keys[1:100])
Error in read_rnbt(rawdata) : 
  Malformed NBT data with tag `128`: at nbt.c, line 251.

> nbt <- rbedrock::get_nbt_data(db, chunk_keys[100:101])
Error in read_rnbt(rawdata) : Malformed NBT data: at nbt.c, line 259.

> nbt <- rbedrock::get_nbt_data(db, chunk_keys[200:201])
Error in read_rnbt(rawdata) : 
  Malformed NBT data with tag `0`: at nbt.c, line 278.

> nbt <- rbedrock::get_nbt_data(db, chunk_keys[1000:1001])
Error in read_rnbt(rawdata) : 
  Malformed NBT data with tag `40`: at nbt.c, line 251.
```

Also, here's a link to a copy of the world in question: https://drive.google.com/file/d/1TrRhRZL3aPMxD3H-1eNHle_VsSKKcfZ1/view?usp=sharing

I've known about R for years, but this is my first real dive into it, so I don't exactly feel at home finding helpful debug information, or digging too deep past the simple log output in RStudio, but if you need anything else from me and point me in the right direction, I'd be more than happy to try and use that as a learning experience and provide what you need.

Also, unrelated, but if you happen to know of any really good learning resources for R programming, preferably some that assume the learner has a lot of prior programming experience in other languages, I'd love to get your suggestions.

Thanks for writing and maintaining rbedrock - such an awesome utility for those of us with a bit of programming ability.

**Comment by reedacartwright** [comment]
I think you are trying to parse data that isn't NBT formatted. rbedrock has functions to parse different types of data formats. There's a specific block API, for instance.

Most of the resources I know of are for novice programmers. The tidyverse book might be helpful to you. https://www.tidyverse.org/learn/

**Comment by Inkybro** [comment]
Crap did I pull the old "I'm not very experienced so let me make an issue about expected behavior" on you? Sorry! I was worried that would be the case.

What you're saying makes complete sense - I am basically trying to do something I am not allowed to by the API (extract NBT data where there is none), and so the error message is in fact expected behavior. I appreciate that clarification!

I guess I could try just sharing what I'm really trying to do: Find a lost horse.

I want to search all chunks for horse entities and turn that into a .csv or something that I can take outside of R-land and play with where I'm more comfortable. Pretty sure the horse is forever lost, but I thought it'd be a fun project to play with R/rbedrock a bit.

I've been able to get a lot of this working, when I work with a small set of chunk keys which I know have horses, but I have not been able to figure out how to essentially iterate all the keys and get the ones with horses.

I would share my attempts with you, but I - for the life of me - cannot find them now. 

Is there some sort of function provided by rbedrock, to determine whether or not a given chunk key has NBT data present? That might get me where I need to be.

I need to try re-watching the livestreams where you demonstrate rbedrock, too. I might find some insight in there, as well.

Thanks again!

**Comment by reedacartwright** [comment]
I think we can help you find the horse if it still exists in the world. I
recommend joining my discord. It'll be easier to help you there.

https://discord.gg/wPxK4Uve
